version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/mail/manage.py migrate --noinput && python /code/mail/manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "cd /code/mail && celery -A mail worker -l info"
    volumes:
      - .:/code
    depends_on:
      - redis
